app/models.py
from datetime import datetime
from hashlib import md5
from werkzeug.security import generate_password_hash, check_password_hash

from flask_login import UserMixin

from app import db, login


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    email = db.Column(db.String(120), index=True, unique=True)
    password_hash = db.Column(db.String(128))
    posts = db.relationship('Post', backref='author', lazy='dynamic')
    about_me = db.Column(db.String(140))
    last_seen = db.Column(db.DateTime, default=datetime.utcnow())

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    def avatar(self, size):
        digest = md5(self.email.lower().encode('utf-8')).hexdigest()
        return 'https://www.gravatar.com/avatar/{}?d=identicon&s={}'.format(digest, size)

    def __repr__(self):
        return '<User {}>'.format(self.username)


@login.user_loader
def load_user(id):
    return User.query.get(int(id))


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    body = db.Column(db.String(140))
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    def __repr__(self):
        return '<Post {}>'.format(self.body)

app/main/forms.py
from flask_wtf import FlaskForm

from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired, Length


class EditProfileForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    about_me = TextAreaField('About me', validators=[Length(min=0, max=140)])
    submit = SubmitField('Submit')

app/__init__.py
# from flask_bootstrap import Bootstrap, current_app
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

from flask import Flask

from config import Config

db = SQLAlchemy()
migrate = Migrate()
login = LoginManager()
login.login_view = 'auth.login'
# bootstrap = Bootstrap()


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    db.init_app(app)
    migrate.init_app(app, db)
    login.init_app(app)
    # bootstrap.init_app(app)

    from app import routes
    app.register_blueprint(routes.bp)

    from app.auth import bp as auth_bp
    app.register_blueprint(auth_bp)

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    from app.reports import bp as reports_bp
    app.register_blueprint(reports_bp)

    return app


from app import models

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from . import routes
# from . import forms

app/main/routes.py
from datetime import datetime

from flask import render_template, flash, request, redirect, url_for

from flask_login import login_required, current_user

from app import db
from app.main import bp
from app.main.forms import EditProfileForm
from app.models import User


@bp.before_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.utcnow()
        db.session.commit()


@bp.route('/user/<username>')
@login_required
def user(username):
    user = User.query.filter_by(username=username).first_or_404()
    posts = [
        {'author': user, 'body': 'Test post #1'},
        {'author': user, 'body': 'Test post #2'},
    ]
    return render_template('main/user.html', user=user, posts=posts)


@bp.route('/edit_profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.about_me = form.about_me.data
        db.session.commit()
        flash('Your changes have been saved.')
        return redirect(url_for('main.edit_profile'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.about_me.data = current_user.about_me
    return render_template('main/edit_profile.html', title='Edit Profile',
                           form=form)

app/reports/__init__.py
from flask import Blueprint

bp = Blueprint('reports', __name__)

from . import routes

app/reports/routes.py
import io
from datetime import datetime
import mimetypes
# import

from flask import render_template, Response, send_file
from flask_login import login_required

import xlsxwriter

from app import db
from . import bp


# @bp.route('/')
@bp.route('/reports')
@login_required
def index():
    # user = User.query.filter_by(username='natalya').first_or_404()
    # posts = [
    #     {
    #         'author': User.query.filter_by(username='natalya').first(),
    #         'body': 'Beautiful day in Portland!'
    #     },
    #     {
    #         'author': User.query.filter_by(username='susan').first(),
    #         'body': 'The Avengers movie was so cool!'
    #     }
    # ]
    return render_template('reports/index.html', title='Reports', )


def get_simple_table_data():
    # Simulate a more complex table read.
    return [[1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]]


@bp.route('/reports/download')
def get_xslx_for_data():
    # Create an in-memory output file for the new workbook.
    output = io.BytesIO()

    # Even though the final file will be in memory the module uses temp
    # files during assembly for efficiency. To avoid this on servers that
    # don't allow temp files, for example the Google APP Engine, set the
    # 'in_memory' Workbook() constructor option as shown in the docs.
    workbook = xlsxwriter.Workbook(output)
    worksheet = workbook.add_worksheet()

    # Get some data to write to the spreadsheet.
    data = get_simple_table_data()

    # Write some test data.
    for row_num, columns in enumerate(data):
        for col_num, cell_data in enumerate(columns):
            worksheet.write(row_num, col_num, cell_data)

    # Close the workbook before sending the data.
    workbook.close()

    # Rewind the buffer.
    output.seek(0)

    # Set up the Http response.
    filename = 'django_simple.xlsx'
    response = Response(
        output,
        content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',

    )
    response.headers['Content-Disposition'] = 'attachment; filename=%s' % filename

    return response

app/routes.py
from flask import Blueprint, render_template

from flask_login import login_required, current_user

from app.models import User

bp = Blueprint('index', __name__)


@bp.route('/')
@bp.route('/index')
@login_required
def index():
    user = User.query.filter_by(username='natalya').first_or_404()
    posts = [
        {
            'author': User.query.filter_by(username='natalya').first(),
            'body': 'Beautiful day in Portland!'
        },
        {
            'author': User.query.filter_by(username='susan').first(),
            'body': 'The Avengers movie was so cool!'
        }
    ]
    return render_template('index.html', title='Home Page', posts=posts)

app/templates/_post.html
    <table>
        <tr valign="top">
            <td><img src="{{ post.author.avatar(36) }}"></td>
            <td>{{ post.author.username }} says:<br>{{ post.body }}</td>
        </tr>
    </table>

app/templates/base.html
<html>
    <head>
        {% if title %}
        <title>{{ title }} - microblog</title>
        {% else %}
        <title>microblog</title>
        {% endif %}
    </head>
    <body>
        <div>
            Microblog:
            <a href="{{ url_for('index.index') }}">Home</a>
            <a href="{{ url_for('reports.index') }}">Reports</a>
            {% if current_user.is_anonymous %}
            <a href="{{ url_for('auth.login') }}">Login</a>
            {% else %}
            <a href="{{ url_for('main.user', username=current_user.username) }}">Profile</a>
            <a href="{{ url_for('auth.logout') }}">Logout</a>
            {% endif %}
        </div>
        <hr>
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <ul>
            {% for message in messages %}
            <li>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        {% endwith %}
        {% block content %}{% endblock %}
    </body>
</html>

app/templates/index.html
{% extends "base.html" %}

{% block content %}
    <h1>Hi, {{ current_user.username }}!</h1>
    {% for post in posts %}
    {% include '_post.html' %}
    {% endfor %}
{% endblock %}

app/templates/main/edit_profile.html
{% extends "base.html" %}

{% block content %}
    <h1>Edit Profile</h1>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.username.label }}<br>
            {{ form.username(size=32) }}<br>
            {% for error in form.username.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.about_me.label }}<br>
            {{ form.about_me(cols=50, rows=4) }}<br>
            {% for error in form.about_me.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}

app/templates/main/user.html
{% extends "base.html" %}

{% block content %}
    <table>
    <tr valign="top">
        <td><img src="{{ user.avatar(128) }}"></td>
        <td>
            <h1>User: {{ user.username }}</h1>
            {% if user.about_me %}<p>{{ user.about_me }}</p>{% endif %}
            {% if user.last_seen %}<p>Last seen on: {{ user.last_seen }}</p>{% endif %}
            {% if user == current_user %}
                <p><a href="{{ url_for('main.edit_profile') }}">Edit your profile</a></p>
            {% endif %}
        </td>
    </tr>
    </table>
    <hr>
    {% for post in posts %}
    {% include '_post.html' %}
    {% endfor %}
{% endblock %}

app/templates/reports/index.html
{% extends "base.html" %}

{% block content %}
    <h1>Reports</h1>
    <a href="{{ url_for('reports.get_xslx_for_data') }}">download Reports</a>

{% endblock %}